---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# stmprevalence: Inspect relation between prevalence covariates and topic proportions

This package provides additional approaches and functions to examine the link between prevalence covariates and topic proportions. Namely, these are:
\begin{itemize}
\item Implementation of the method of composition, using either a quasibinomial GLM or a beta regression. Note that the method of composition is implemented in the stm package, through its estimateEffect function, employing a simple OLS regression. However, this violates the assumption of (sampled) topic proportions being restricted to (0,1). 
\item Direct assessment of the prevalence output produced by the stm, i.e. the MAP estimates for $\Gamma$ and $\Sigma$, by sampling from a LogisticNormal distribution.
\end{itemize}

Both approaches can be used to visualize the empirical mean as well as credible intervals of topic proportions for the full observed range of a specified variable, while holding all other variables as mean/majority vote.

# Installation
